
# Use uma imagem base oficial do Node.js para frontend
FROM node:18 as build

# Definir diretório de trabalho no container
WORKDIR /usr/src/app

# Copiar arquivos de dependências
COPY frontend/package*.json ./

# Instalar dependências
RUN npm install

# Copiar restante do código
COPY frontend .

# Build da aplicação
RUN npm run build

# Usar uma imagem leve para servir a aplicação
FROM nginx:alpine

# Copiar build gerado para o nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expor porta padrão do Nginx
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
