
version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2g"
        reservations:
          cpus: "1.0"
          memory: "1g"
      replicas: 4  # Número inicial de instâncias, pode ser escalado
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

databases:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
